Tired of seeing wrong description when linking this page
2009scape/2009scape.github.io pull request #55
Opened 2021-03-18 21:29 UTC by summerdevs

2021-03-19 00:01 UTC, summerdevs commented
Okay, I also moved the exclusive pages such as commands and skill cape perks into the 2009exclusive folder and changed the links that linked them to the main exclusive_guides page.

2021-03-20 14:48 UTC, dginovker requested changes

2021-03-20 14:48 UTC, dginovker commented on site/kbase/guid/exclusive_guides.html
> +                <li><a href="./../../rules/rules.html" class="fly"><span>Rules</span></a></li>
Not merging. Only change Menubox with Find and Replace

2021-03-20 16:30 UTC, summerdevs commented on site/kbase/guid/exclusive_guides.html
> +                <li><a href="./../../rules/rules.html" class="fly"><span>Rules</span></a></li>
Okay then? I just won't add it. Because you still neglected to answer how I do this without broken links everywhere.

2021-03-20 16:30 UTC, closed without merging